language: node_js
node_js:
  - stable
install:
  - npm install
  - npm run bootstrap
before_script:
  - npm run build
script:
  # Lint last commit message from history
  - npx commitlint --from=HEAD~1
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
notifications:
  email: false
